### ISSUE TITLE
14 classifier model

### ISSUE THREAD

**Issue by RedMoon32** [sunghyunjun/kaggle-vinbigdata-chest-xray-abnormalities-detection#1]
Hello! Do you have pretrained weights for 14 classifier? If so, could you please tell me about the normalization and size used?

**Comment by RedMoon32** [comment]
Also, which performance did you get (f1 score) when training it? (14-classifier)

**Comment by RedMoon32** [comment]
I mean classification of whole image only, no detection

**Comment by sunghyunjun** [comment]
Hello! I'm sorry but I don't have the pretrained weights for 14 classifier of image only.

**Comment by RedMoon32** [comment]
Ok, I am training my own now
In your opinion, is it possible to achieve f1 > 80% for majority of the classes in simple 80-20% train-test split?

**Comment by sunghyunjun** [comment]
I'm not sure you can achieve f1 more than 80% because I didn't do experiment with 14 class. But I think you can get good results.

You may know this paper [[ChestX-ray8: Hospital-scale Chest X-ray Database and Benchmarks on Weakly-Supervised Classification and Localization of Common Thorax Diseases]](https://arxiv.org/abs/1705.02315). You can find f1 score over 0.8 on Table 2.

And these are average precision at 0.4 iou of 14-class detector (not classifier). You may check various AP by the class.

|Class|AP at 0.4 iou, model=d5-896px|
|:-:|:-:|
|Aortic enlargement| 0.937414994942938|
|Atelectasis| 0.288444957947506|
|Calcification| 0.22799071417370925|
|Cardiomegaly| 0.9445964843392058|
|Consolidation| 0.43976404105246325|
|ILD| 0.3974172076551769|
|Infiltration| 0.4042867652160543|
|Lung Opacity| 0.3996761780147463|
|Nodule Mass| 0.3638061290133979|
|Other lesion| 0.1466003924397974|
|Pleural effusion| 0.6292744736480345|
|Pleural thickening| 0.3679077313687412|
|Pneumothorax| 0.30033675631345635|
|Pulmonary fibrosis| 0.448065471927376|
